/**
 * Console-noise filtering for the E2E suite.
 *
 * A page that logs an error is a page that ships a defect, so the smoke tests
 * fail on any console error. The allowlist below covers only messages that a
 * static build legitimately produces when an optional artifact is absent; the
 * paired `REQUIRED_ASSETS` matcher keeps real regressions loud.
 */

export interface ConsoleMessage {
  type: string;
  text: string;
}

/**
 * Messages that do not indicate a defect.
 *
 * Each entry is anchored to something the build genuinely may omit, so a new
 * error of any other shape still fails the run.
 */
const BENIGN: RegExp[] = [
  // The search index is written by a separate build step; without it the dialog
  // shows its "index unavailable" copy, which is the designed degradation.
  /\/pagefind\/[^\s"']*/,
  // Icons are generated by the icons script and are not in a bare checkout.
  /\/apple-touch-icon\.png/,
  /\/manifest\.webmanifest/
];

export function isConsoleFailure(message: ConsoleMessage): boolean {
  if (message.type !== "error" && message.type !== "warning") return false;
  return !BENIGN.some((pattern) => pattern.test(message.text));
}

export function consoleFailures(messages: readonly ConsoleMessage[]): ConsoleMessage[] {
  return messages.filter(isConsoleFailure);
}

/** Human-readable list for an assertion message. */
export function describeConsoleFailures(messages: readonly ConsoleMessage[]): string {
  return messages.map((message) => `[${message.type}] ${message.text}`).join("\n");
}
