#title in header
title: "Hi Folks."

#main info
#owner
owner: "I am Koh Hom(许峰)⛰️"
email: xff9924@gmail.com
info: "99年生人，潮汕人。本科就读于华南师范大学网络工程专业。曾在蚂蚁集团-体验技术部、字节跳动-今日头条部门实习。毕业后先后在新加坡Shopee、TikTok工作至今。"
#description
desc: "A software engineer from Chaoshan, China. Graduated from South China Normal University (SCNU) with a degree in Network Engineering. Interned at Ant Group and ByteDance. Now working at TikTok in Singapore. Welcome to my blog! Hope you enjoy it😊 ."

#menu
menu:
  Works: /Works
  About: /About
  Links: /Links

#index/main page max show posts (in number)
max_post: 12

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/clean99
linkedin: https://www.linkedin.com/in/hom-koh-42019a204
twitter: https://twitter.com/Clean993
instagram: https://www.instagram.com/xu.feng.7712/

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io

links:
  test: www.test.com
